language: python
python:
  - "2.7.12"
  - "3.4"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "2.7.12"
    - python: "3.7-dev"

install:
  - pip install nose Faker codecov
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=telium test/*.py"

after_success:
  - codecov